import logging
import time
import sys
from datetime import datetime, timezone
from typing import Dict, List, Optional

from core.config import (
    PAPER_ATTR_TABLE_NAME,
    PUBLIC_CORPUS_TABLE_NAME,
)
from core.embedder import Embedder
from core.supabase_uploader import SupabaseUploader
from core.metrics import MetricsTracker
from orm.paper_attr_row import PaperAttrRow
from orm.publ_corpus_row import PublCorpusRow

from .arxiv_embedder import ArxivEmbedder
from .oai_client import request_listrecords, iter_records
from .state import load_state, save_state, state_path
from .mapping import to_paper_attr_row, build_publ_row
from .cli import parse_args

logging.basicConfig(level=logging.INFO)
logging.getLogger("httpx").propagate = False
logger = logging.getLogger(__name__)

def run(args) -> None:
    st_path = state_path(args.out, args.state)

    # Initialize state (resume if requested)
    if args.resume:
        st: Dict = load_state(st_path) or {}
    else:
        st = {}

    resumption_token: Optional[str] = st.get("resumption_token")
    total_written = int(st.get("total_written", 0))
    # Track the original --from argument separately from progress 'from'
    original_from = st.get("original_from") if "original_from" in st else args.from_date
    started_from = st.get("from") or original_from
    started_until = st.get("until") or args.until_date
    started_set = st.get("set") or args.set_spec
    started_prefix = st.get("metadata_prefix") or args.metadata_prefix

    # Respect immutable run parameters when resuming
    if args.resume and st:
        # Compare immutable parameters; allow 'from' to progress by comparing against original_from only
        from_mismatch = False
        if args.from_date is not None:
            saved_original_from = st.get("original_from", st.get("from"))
            from_mismatch = saved_original_from != args.from_date
        if (st.get("metadata_prefix") and st["metadata_prefix"] != args.metadata_prefix) or \
           from_mismatch or \
           (st.get("until") and st["until"] != args.until_date) or \
           (st.get("set") and st["set"] != args.set_spec):
            print("State/run parameter mismatch. Refuse to resume with different parameters.", file=sys.stderr)
            sys.exit(2)

    # Prepare Supabase uploader and Embedder
    embedder = Embedder() # TODO: make device configurable
    arxiv_embedder = ArxivEmbedder(embedder)
    supa = SupabaseUploader()
    tracker = MetricsTracker()
    tracker.start()

    while True:
        print('top of loop')
        if resumption_token:
            params = {"verb": "ListRecords", "resumptionToken": resumption_token}
        else:
            params = {
                "verb": "ListRecords",
                "metadataPrefix": started_prefix,
            }
            if started_from:
                params["from"] = started_from
            if started_until:
                params["until"] = started_until
            if started_set:
                params["set"] = started_set

        # record request time
        request_start = datetime.now(timezone.utc)
        xml_text = request_listrecords(params, timeout=args.timeout, max_retries=args.max_retries)
        records_iter, next_token = iter_records(xml_text)

        # Transform to PaperAttrRow and PublCorpusRow rows
        paper_rows: List[PaperAttrRow] = []
        publ_rows: List[PublCorpusRow] = []
        page_seen = 0
        last_datestamp: Optional[str] = None
        for rec in records_iter:
            page_seen += 1
            if rec.get("deleted"):
                continue
            with tracker.record_timer():
                row: PaperAttrRow = to_paper_attr_row(rec)
                paper_rows.append(row)

                # Build publ_corpus row; FTS is generated by DB, so omit it
                publ: PublCorpusRow = build_publ_row(row, rec)
                publ_rows.append(publ)
                total_written += 1
                # Track most recent datestamp seen (simple overwrite; no ordering checks)
                ds = rec.get("datestamp")
                if ds:
                    last_datestamp = ds
            if args.max_records and total_written >= args.max_records:
                # Upload any accumulated rows before exiting

                # First, embed the new publ_rows
                arxiv_embedder.embed_publ_rows(publ_rows, paper_rows)
                # Now upload to both tables
                try:
                    if paper_rows:
                        supa.upload_rows(rows=paper_rows, table_name=PAPER_ATTR_TABLE_NAME)
                    if publ_rows:
                        supa.upload_rows(rows=publ_rows, table_name=PUBLIC_CORPUS_TABLE_NAME, primary_key="paper_id", batch_size=500)
                except Exception as e:
                    print(f"Error: batch upload failed near max_records limit: {e}")
                    raise RuntimeError(f"Batch upload failed near max_records limit: {e}") from e

                # Save state and exit
                st.update({
                    "resumption_token": resumption_token, # Keep current token for resumption; will overlap but safe
                    "total_written": total_written,
                    # Persist progress 'from' as the most recently seen datestamp (fallback to current started_from)
                    "from": last_datestamp or started_from,
                    "original_from": original_from,
                    "until": started_until,
                    "set": started_set,
                    "metadata_prefix": started_prefix,
                    "last_saved": datetime.now(timezone.utc).isoformat()
                })
                save_state(st_path, st)
                print(f"Reached max_records={args.max_records}. Uploaded {total_written} PaperAttr rows.")
                tracker.stop()
                tracker.log_summary(logger)
                return

        # Upload page rows in batch
        uploaded_paper = 0
        uploaded_publ = 0
        if paper_rows:
            try:
                supa.upload_rows(rows=paper_rows, table_name=PAPER_ATTR_TABLE_NAME)
                uploaded_paper = len(paper_rows)
            except Exception as e:
                logger.error(f"Batch upload failed, aborting: {e}")
                raise RuntimeError(f"Batch upload failed for paper_attrs ({len(paper_rows)} rows): {e}; aborting.") from e

        if publ_rows:
            try:
                # First, embed the new publ_rows
                arxiv_embedder.embed_publ_rows(publ_rows, paper_rows)
                # Now upload to publ_corpus
                supa.upload_rows(rows=publ_rows, table_name=PUBLIC_CORPUS_TABLE_NAME, primary_key="paper_id", batch_size=500)
                uploaded_publ = len(publ_rows)
            except Exception as e:
                logger.error(f"Batch upload failed, aborting: {e}")
                raise RuntimeError(f"Batch upload failed for publ_corpus ({len(publ_rows)} rows): {e}; aborting.") from e

        # Update state after each page
        st.update({
            "resumption_token": next_token,
            "total_written": total_written,
            # Update progress 'from' to last seen datestamp on this page (fallback to current started_from)
            "from": last_datestamp or started_from,
            "original_from": original_from,
            "until": started_until,
            "set": started_set,
            "metadata_prefix": started_prefix,
            "last_saved": datetime.now(timezone.utc).isoformat(),
        })
        save_state(st_path, st)

        # Progress log
        logger.info(f"Processed {page_seen} records; uploaded paper_attrs={uploaded_paper}, publ_corpus={uploaded_publ}; total_papers={total_written}; next_token={'present' if next_token else 'none'}")
        tracker.log_summary(logger)

        if not next_token:
            print("No more pages. Harvest complete.")
            break
        resumption_token = next_token

        # Polite delay
        # check elapsed time to avoid sleeping too long
        elapsed = (datetime.now(timezone.utc) - request_start).total_seconds()
        if elapsed < args.sleep:
            remaining_sleep = args.sleep - elapsed
            print(f"Sleeping {remaining_sleep:.1f}s before next request...")
            time.sleep(remaining_sleep)

    # Final metrics after completion
    tracker.stop()
    tracker.log_summary(logger)


def main() -> None:
    args = parse_args()
    run(args)


if __name__ == "__main__":
    main()
