name: Trigger auto deployment for sevenfold-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ prod ]
    paths:
    - '**'
    - '.github/workflows/sevenfold-api-AutoDeployTrigger-e5fbb458-3b72-4716-9746-26ed7cfd2c40.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.SEVENFOLDAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SEVENFOLDAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SEVENFOLDAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/api
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: sevenfoldapiregistry.azurecr.io
          registryUsername: ${{ secrets.SEVENFOLDAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SEVENFOLDAPI_REGISTRY_PASSWORD }}
          containerAppName: sevenfold-api
          resourceGroup: sevenfold-rg
          imageToBuild: sevenfoldapiregistry.azurecr.io/sevenfold-api:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


